### ISSUE TITLE
Exposed MailGun API Key

### ISSUE THREAD

**Issue by gitty8** [nkadel/samba-4.13.x-srpm#2]
Potential security breach. See /samba.spec

**Comment by nkadel** [comment]
samba.spec is 5827 lines long, Can you give me a better hint here?

**Comment by nkadel** [comment]
No comment for a year, no hint of what the actual key exposure is here. Mailgun is a very distinct service with multiple key API's, and a distinct tool from Samba, I can't reasonably chase down a non-specific ticket like this.
